ENABLE_DEBUG_LOGS = false
REPLACE_GENERATED_SPAWNERS_WITH_COBBLEMON_SPAWNERS = true
REPLACE_SPAWNERS_IN_STRUCTURES_WITH_COBBLEMON_SPAWNERS = true
REPLACE_SPAWNERS_OUTSIDE_OF_STRUCTURES_WITH_DEFAULT_COBBLEMON_SPAWNERS = true
REPLACE_ANY_UNSPECIFIED_SPAWNERS_WITH_DEFAULT_COBBLEMON_SPAWNERS = false
ALLOW_SPAWNED_POKEMON_TO_BE_CATCHABLE = false
ALLOW_SPAWNED_POKEMON_TO_BE_DEFEATED_OUTSIDE_OF_BATTLE = false
